Fix a bug in the RichText field indexer.
The bug occurs if the RichText field does not define a default value.

The bug was introduced in 2.2.0 and caused no other field of the behavior to be indexed, because an AttributeError ('NoneType' object has no attribute 'output') would occur in the RichText indexer.